### ISSUE TITLE
Filter out dev-dependencies

### ISSUE THREAD

**Issue by bvssvni** [maxsnew/cargo-dot#13]
It would be nice if there was a way to filter out dev-dependencies such that the generated graph resembled the dependency structure you need to use the library.

**Comment by bvssvni** [comment]
It doesn't look like Cargo.lock differs between dependencies and dev-dependencies.

**Comment by kbknapp** [comment]
@bvssvni I don't know if this repo is maintained any more, so I've started [a fork](https://github.com/kbknapp/cargo-graph) which does exactly this.

**Comment by bvssvni** [comment]
@kbknapp Oh nice!

**Comment by maxsnew** [comment]
Closed because I'm deprecating in favor of the fork.
