### ISSUE TITLE
Error building on OSX

### ISSUE THREAD

**Issue by bvssvni** [maxsnew/cargo-dot#7]
`rustc 1.0.0-nightly (30e1f9a1c 2015-03-14) (built 2015-03-15)`
`cargo 0.0.1-pre-nightly (07cd618 2015-03-12) (built 2015-03-13)`

```
/Users/sven/.cargo/git/checkouts/cargo-2f7f63790bcc5cbc/master/src/cargo/util/paths.rs:30:35: 30:52 error: `Component::Prefix` does not name a structure
/Users/sven/.cargo/git/checkouts/cargo-2f7f63790bcc5cbc/master/src/cargo/util/paths.rs:30     let mut ret = if let Some(c @ Component::Prefix { .. }) = components.peek() {
                                                                                                                            ^~~~~~~~~~~~~~~~~
/Users/sven/.cargo/git/checkouts/cargo-2f7f63790bcc5cbc/master/src/cargo/util/paths.rs:39:13: 39:30 error: `Component::Prefix` does not name a structure
/Users/sven/.cargo/git/checkouts/cargo-2f7f63790bcc5cbc/master/src/cargo/util/paths.rs:39             Component::Prefix { .. } => unreachable!(),
                                                                                                      ^~~~~~~~~~~~~~~~~
/Users/sven/.cargo/git/checkouts/cargo-2f7f63790bcc5cbc/master/src/cargo/util/paths.rs:40:13: 40:29 error: unresolved enum variant, struct or const `Empty`
/Users/sven/.cargo/git/checkouts/cargo-2f7f63790bcc5cbc/master/src/cargo/util/paths.rs:40             Component::Empty => { ret.push(""); }
                                                                                                      ^~~~~~~~~~~~~~~~
error: aborting due to 3 previous errors
Could not compile `cargo`.
```

**Comment by maxsnew** [comment]
Yeah I get the same issue right now. I know it's not ideal, but see the README for an explanation. 
Basically the Cargo repo is usually a few days behind the rustc nightly so we get in states where you can't build this repo with the nightly. Some options:

1. Patch Cargo and send them a pr, point me to the patched version and I can depend on that. This usually works for about a day at a time.
2. Figure out a cargo commit that works with rustc alpha 2 or some other pegged version.
3. Wait until the beta when things should be more stable. [This](http://blog.rust-lang.org/2015/02/13/Final-1.0-timeline.html) says it's pretty soon, end of the month.

**Comment by maxsnew** [comment]
I found a pr that makes cargo build now, so for today at least 1 is already done. A few other things broke, though so I'll fix them and push a working version (at least for today!).

**Comment by maxsnew** [comment]
Ok it should be working now
