### ISSUE TITLE
Invalid arguments

### ISSUE THREAD

**Issue by bvssvni** [maxsnew/cargo-dot#8]
I get this:

```
$ cargo dot > Cargo.dot
Invalid arguments.

Usage: cargo dot [options]
       cargo dot --help
```

**Comment by maxsnew** [comment]
I can't replicate this. I've got `rustc 1.0.0-nightly (30e1f9a1c 2015-03-14) (built 2015-03-15)` and `cargo 0.0.1-pre-nightly (07cd618 2015-03-12) (built 2015-03-14)`

Maybe you have an old `cargo-dot` on your path? Cargo has changed the way they pass command line arguments a few times and I would get this error.

**Comment by maxsnew** [comment]
Closing as non reproducible. I've pushed a new version just now. Let me know if it's not working with the nightly.

**Comment by bvssvni** [comment]
Works by removing the copy I had in `/usr/loca/bin`.
